export const countries = [
  { country: "Afghanistan", code: "af", path: "image/flag/af.svg" },
  { country: "Albania", code: "al", path: "image/flag/al.svg" },
  { country: "Algeria", code: "dz", path: "image/flag/dz.svg" },
  { country: "Andorra", code: "ad", path: "image/flag/ad.svg" },
  { country: "Angola", code: "ao", path: "image/flag/ao.svg" },
  {
    country: "Antigua and Barbuda",
    code: "ag",
    path: "image/flag/ag.svg",
  },
  { country: "Argentina", code: "ar", path: "image/flag/ar.svg" },
  { country: "Armenia", code: "am", path: "image/flag/am.svg" },
  { country: "Australia", code: "au", path: "image/flag/au.svg" },
  { country: "Austria", code: "at", path: "image/flag/at.svg" },
  { country: "Azerbaijan", code: "az", path: "image/flag/az.svg" },
  { country: "Bahamas", code: "bs", path: "image/flag/bs.svg" },
  { country: "Bahrain", code: "bh", path: "image/flag/bh.svg" },
  { country: "Bangladesh", code: "bd", path: "image/flag/bd.svg" },
  { country: "Barbados", code: "bb", path: "image/flag/bb.svg" },
  { country: "Belarus", code: "by", path: "image/flag/by.svg" },
  { country: "Belgium", code: "be", path: "image/flag/be.svg" },
  { country: "Belize", code: "bz", path: "image/flag/bz.svg" },
  { country: "Benin", code: "bj", path: "image/flag/bj.svg" },
  { country: "Bhutan", code: "bt", path: "image/flag/bt.svg" },
  { country: "Bolivia", code: "bo", path: "image/flag/bo.svg" },
  {
    country: "Bosnia and Herzegovina",
    code: "ba",
    path: "image/flag/ba.svg",
  },
  { country: "Botswana", code: "bw", path: "image/flag/bw.svg" },
  { country: "Brazil", code: "br", path: "image/flag/br.svg" },
  {
    country: "Brunei Darussalam",
    code: "bn",
    path: "image/flag/bn.svg",
  },
  { country: "Bulgaria", code: "bg", path: "image/flag/bg.svg" },
  { country: "Burkina Faso", code: "bf", path: "image/flag/bf.svg" },
  { country: "Burundi", code: "bi", path: "image/flag/bi.svg" },
  { country: "Cabo Verde", code: "cv", path: "image/flag/cv.svg" },
  { country: "Cambodia", code: "kh", path: "image/flag/kh.svg" },
  { country: "Cameroon", code: "cm", path: "image/flag/cm.svg" },
  { country: "Canada", code: "ca", path: "image/flag/ca.svg" },
  {
    country: "Central African Republic",
    code: "cf",
    path: "image/flag/cf.svg",
  },
  { country: "Chad", code: "td", path: "image/flag/td.svg" },
  { country: "Chile", code: "cl", path: "image/flag/cl.svg" },
  { country: "China", code: "cn", path: "image/flag/cn.svg" },
  { country: "Colombia", code: "co", path: "image/flag/co.svg" },
  { country: "Comoros", code: "km", path: "image/flag/km.svg" },
  { country: "Congo", code: "cg", path: "image/flag/cg.svg" },
  {
    country: "Congo, Democratic Republic of the",
    code: "cd",
    path: "image/flag/cd.svg",
  },
  { country: "Costa Rica", code: "cr", path: "image/flag/cr.svg" },
  { country: "Croatia", code: "hr", path: "image/flag/hr.svg" },
  { country: "Cuba", code: "cu", path: "image/flag/cu.svg" },
  { country: "Cyprus", code: "cy", path: "image/flag/cy.svg" },
  { country: "Czech Republic", code: "cz", path: "image/flag/cz.svg" },
  { country: "Denmark", code: "dk", path: "image/flag/dk.svg" },
  { country: "Djibouti", code: "dj", path: "image/flag/dj.svg" },
  { country: "Dominica", code: "dm", path: "image/flag/dm.svg" },
  {
    country: "Dominican Republic",
    code: "do",
    path: "image/flag/do.svg",
  },
  { country: "Ecuador", code: "ec", path: "image/flag/ec.svg" },
  { country: "Egypt", code: "eg", path: "image/flag/eg.svg" },
  { country: "El Salvador", code: "sv", path: "image/flag/sv.svg" },
  {
    country: "Equatorial Guinea",
    code: "gq",
    path: "image/flag/gq.svg",
  },
  { country: "Eritrea", code: "er", path: "image/flag/er.svg" },
  { country: "Estonia", code: "ee", path: "image/flag/ee.svg" },
  { country: "Eswatini", code: "sz", path: "image/flag/sz.svg" },
  { country: "Ethiopia", code: "et", path: "image/flag/et.svg" },
  { country: "Fiji", code: "fj", path: "image/flag/fj.svg" },
  { country: "Finland", code: "fi", path: "image/flag/fi.svg" },
  { country: "France", code: "fr", path: "image/flag/fr.svg" },
  { country: "Gabon", code: "ga", path: "image/flag/ga.svg" },
  { country: "Gambia", code: "gm", path: "image/flag/gm.svg" },
  { country: "Georgia", code: "ge", path: "image/flag/ge.svg" },
  { country: "Germany", code: "de", path: "image/flag/de.svg" },
  { country: "Ghana", code: "gh", path: "image/flag/gh.svg" },
  { country: "Greece", code: "gr", path: "image/flag/gr.svg" },
  { country: "Grenada", code: "gd", path: "image/flag/gd.svg" },
  { country: "Guatemala", code: "gt", path: "image/flag/gt.svg" },
  { country: "Guinea", code: "gn", path: "image/flag/gn.svg" },
  { country: "Guinea-Bissau", code: "gw", path: "image/flag/gw.svg" },
  { country: "Guyana", code: "gy", path: "image/flag/gy.svg" },
  { country: "Haiti", code: "ht", path: "image/flag/ht.svg" },
  { country: "Honduras", code: "hn", path: "image/flag/hn.svg" },
  { country: "Hungary", code: "hu", path: "image/flag/hu.svg" },
  { country: "Iceland", code: "is", path: "image/flag/is.svg" },
  { country: "India", code: "in", path: "image/flag/in.svg" },
  { country: "Indonesia", code: "id", path: "image/flag/id.svg" },
  { country: "Iran", code: "ir", path: "image/flag/ir.svg" },
  { country: "Iraq", code: "iq", path: "image/flag/iq.svg" },
  { country: "Ireland", code: "ie", path: "image/flag/ie.svg" },
  { country: "Israel", code: "il", path: "image/flag/il.svg" },
  { country: "Italy", code: "it", path: "image/flag/it.svg" },
  { country: "Jamaica", code: "jm", path: "image/flag/jm.svg" },
  { country: "Japan", code: "jp", path: "image/flag/jp.svg" },
  { country: "Jordan", code: "jo", path: "image/flag/jo.svg" },
  { country: "Kazakhstan", code: "kz", path: "image/flag/kz.svg" },
  { country: "Kenya", code: "ke", path: "image/flag/ke.svg" },
  { country: "Kiribati", code: "ki", path: "image/flag/ki.svg" },
  {
    country: "Korea, Democratic People's Republic of",
    code: "kp",
    path: "image/flag/kp.svg",
  },
  {
    country: "Korea, Republic of",
    code: "kr",
    path: "image/flag/kr.svg",
  },
  { country: "Kuwait", code: "kw", path: "image/flag/kw.svg" },
  { country: "Kyrgyzstan", code: "kg", path: "image/flag/kg.svg" },
  {
    country: "Lao People's Democratic Republic",
    code: "la",
    path: "image/flag/la.svg",
  },
  { country: "Latvia", code: "lv", path: "image/flag/lv.svg" },
  { country: "Lebanon", code: "lb", path: "image/flag/lb.svg" },
  { country: "Lesotho", code: "ls", path: "image/flag/ls.svg" },
  { country: "Liberia", code: "lr", path: "image/flag/lr.svg" },
  { country: "Libya", code: "ly", path: "image/flag/ly.svg" },
  { country: "Liechtenstein", code: "li", path: "image/flag/li.svg" },
  { country: "Lithuania", code: "lt", path: "image/flag/lt.svg" },
  { country: "Luxembourg", code: "lu", path: "image/flag/lu.svg" },
  { country: "Madagascar", code: "mg", path: "image/flag/mg.svg" },
  { country: "Malawi", code: "mw", path: "image/flag/mw.svg" },
  { country: "Malaysia", code: "my", path: "image/flag/my.svg" },
  { country: "Maldives", code: "mv", path: "image/flag/mv.svg" },
  { country: "Mali", code: "ml", path: "image/flag/ml.svg" },
  { country: "Malta", code: "mt", path: "image/flag/mt.svg" },
  {
    country: "Marshall Islands",
    code: "mh",
    path: "image/flag/mh.svg",
  },
  { country: "Mauritania", code: "mr", path: "image/flag/mr.svg" },
  { country: "Mauritius", code: "mu", path: "image/flag/mu.svg" },
  { country: "Mexico", code: "mx", path: "image/flag/mx.svg" },
  {
    country: "Micronesia",
    code: "fm",
    path: "image/flag/fm.svg",
  },
  {
    country: "Moldova",
    code: "md",
    path: "image/flag/md.svg",
  },
  { country: "Monaco", code: "mc", path: "image/flag/mc.svg" },
  { country: "Mongolia", code: "mn", path: "image/flag/mn.svg" },
  { country: "Montenegro", code: "me", path: "image/flag/me.svg" },
  { country: "Morocco", code: "ma", path: "image/flag/ma.svg" },
  { country: "Mozambique", code: "mz", path: "image/flag/mz.svg" },
  { country: "Myanmar", code: "mm", path: "image/flag/mm.svg" },
  { country: "Namibia", code: "na", path: "image/flag/na.svg" },
  { country: "Nauru", code: "nr", path: "image/flag/nr.svg" },
  { country: "Nepal", code: "np", path: "image/flag/np.svg" },
  { country: "Netherlands", code: "nl", path: "image/flag/nl.svg" },
  { country: "New Zealand", code: "nz", path: "image/flag/nz.svg" },
  { country: "Nicaragua", code: "ni", path: "image/flag/ni.svg" },
  { country: "Niger", code: "ne", path: "image/flag/ne.svg" },
  { country: "Nigeria", code: "ng", path: "image/flag/ng.svg" },
  { country: "North Macedonia", code: "mk", path: "image/flag/mk.svg" },
  { country: "Norway", code: "no", path: "image/flag/no.svg" },
  { country: "Oman", code: "om", path: "image/flag/om.svg" },
  { country: "Pakistan", code: "pk", path: "image/flag/pk.svg" },
  { country: "Palau", code: "pw", path: "image/flag/pw.svg" },
  {
    country: "Palestine",
    code: "ps",
    path: "image/flag/ps.svg",
  },
  { country: "Panama", code: "pa", path: "image/flag/pa.svg" },
  {
    country: "Papua New Guinea",
    code: "pg",
    path: "image/flag/pg.svg",
  },
  { country: "Paraguay", code: "py", path: "image/flag/py.svg" },
  { country: "Peru", code: "pe", path: "image/flag/pe.svg" },
  { country: "Philippines", code: "ph", path: "image/flag/ph.svg" },
  { country: "Poland", code: "pl", path: "image/flag/pl.svg" },
  { country: "Portugal", code: "pt", path: "image/flag/pt.svg" },
  { country: "Qatar", code: "qa", path: "image/flag/qa.svg" },
  { country: "Romania", code: "ro", path: "image/flag/ro.svg" },
  {
    country: "Russia",
    code: "ru",
    path: "image/flag/ru.svg",
  },
  { country: "Rwanda", code: "rw", path: "image/flag/rw.svg" },
  {
    country: "Saint Kitts and Nevis",
    code: "kn",
    path: "image/flag/kn.svg",
  },
  { country: "Saint Lucia", code: "lc", path: "image/flag/lc.svg" },
  {
    country: "Saint Vincent and the Grenadines",
    code: "vc",
    path: "image/flag/vc.svg",
  },
  { country: "Samoa", code: "ws", path: "image/flag/ws.svg" },
  { country: "San Marino", code: "sm", path: "image/flag/sm.svg" },
  {
    country: "Sao Tome and Principe",
    code: "st",
    path: "image/flag/st.svg",
  },
  { country: "Saudi Arabia", code: "sa", path: "image/flag/sa.svg" },
  { country: "Senegal", code: "sn", path: "image/flag/sn.svg" },
  { country: "Serbia", code: "rs", path: "image/flag/rs.svg" },
  { country: "Seychelles", code: "sc", path: "image/flag/sc.svg" },
  { country: "Sierra Leone", code: "sl", path: "image/flag/sl.svg" },
  { country: "Singapore", code: "sg", path: "image/flag/sg.svg" },
  { country: "Slovakia", code: "sk", path: "image/flag/sk.svg" },
  { country: "Slovenia", code: "si", path: "image/flag/si.svg" },
  { country: "Solomon Islands", code: "sb", path: "image/flag/sb.svg" },
  { country: "Somalia", code: "so", path: "image/flag/so.svg" },
  { country: "South Africa", code: "za", path: "image/flag/za.svg" },
  { country: "South Sudan", code: "ss", path: "image/flag/ss.svg" },
  { country: "Spain", code: "es", path: "image/flag/es.svg" },
  { country: "Sri Lanka", code: "lk", path: "image/flag/lk.svg" },
  { country: "Sudan", code: "sd", path: "image/flag/sd.svg" },
  { country: "Suriname", code: "sr", path: "image/flag/sr.svg" },
  { country: "Sweden", code: "se", path: "image/flag/se.svg" },
  { country: "Switzerland", code: "ch", path: "image/flag/ch.svg" },
  {
    country: "Syria",
    code: "sy",
    path: "image/flag/sy.svg",
  },
  { country: "Tajikistan", code: "tj", path: "image/flag/tj.svg" },
  {
    country: "Tanzania",
    code: "tz",
    path: "image/flag/tz.svg",
  },
  { country: "Thailand", code: "th", path: "image/flag/th.svg" },
  { country: "Timor-Leste", code: "tl", path: "image/flag/tl.svg" },
  { country: "Togo", code: "tg", path: "image/flag/tg.svg" },
  { country: "Tonga", code: "to", path: "image/flag/to.svg" },
  {
    country: "Trinidad and Tobago",
    code: "tt",
    path: "image/flag/tt.svg",
  },
  { country: "Tunisia", code: "tn", path: "image/flag/tn.svg" },
  { country: "Turkey", code: "tr", path: "image/flag/tr.svg" },
  { country: "Turkmenistan", code: "tm", path: "image/flag/tm.svg" },
  { country: "Tuvalu", code: "tv", path: "image/flag/tv.svg" },
  { country: "Uganda", code: "ug", path: "image/flag/ug.svg" },
  { country: "Ukraine", code: "ua", path: "image/flag/ua.svg" },
  {
    country: "UAE",
    code: "ae",
    path: "image/flag/ae.svg",
  },
  {
    country: "UK",
    code: "gb",
    path: "image/flag/gb.svg",
  },
  {
    country: "USA",
    code: "us",
    path: "image/flag/us.svg",
  },
  { country: "Uruguay", code: "uy", path: "image/flag/uy.svg" },
  { country: "Uzbekistan", code: "uz", path: "image/flag/uz.svg" },
  { country: "Vanuatu", code: "vu", path: "image/flag/vu.svg" },
  {
    country: "Venezuela",
    code: "ve",
    path: "image/flag/ve.svg",
  },
  { country: "Vietnam", code: "vn", path: "image/flag/vn.svg" },
  { country: "Yemen", code: "ye", path: "image/flag/ye.svg" },
  { country: "Zambia", code: "zm", path: "image/flag/zm.svg" },
  { country: "Zimbabwe", code: "zw", path: "image/flag/zw.svg" },
];
